Geph updates documentation
whimc/Path-Generator pull request #30
Opened 2022-10-03 18:41 UTC by Geph

Merging all the setup and update documentation into a single file.

2022-10-03 18:50 UTC, jackah2 requested changes

2022-10-03 18:50 UTC, jackah2 commented on setup_update.md
> +# EC2 Setup Guide
I think the setup section should come before the update section in this file

2022-10-03 18:50 UTC, jackah2 commented on setup_update.md
> +Follow the [update guide](./update.md) to see details on applying new changes to the API.
Not needed anymore

2022-10-03 18:50 UTC, jackah2 commented on README.md
> +Can be found in [setup_update.md](https://github.com/whimc/Path-Generator/setup_update.md)
```suggestion
Can be found in [setup_update.md](./setup_update.md)
```
Let's use relative paths here instead

2022-10-03 18:50 UTC, jackah2 commented on setup_update.md
> +6. Run ```systemctl restart path-generator``` to restart the API
This should come after the installation section

2022-10-03 18:50 UTC, jackah2 commented on setup_update.md
> +Follow the [update guide](./update.md) to see details on applying new changes to the API.
Also you should remove the `### Running on Linux server` section at the bottom of the README

2022-10-03 18:50 UTC, jackah2 commented on setup_update.md
> +1. Log into aws.illinois.edu and go to EC2
```suggestion
1. Log into https://aws.illinois.edu and go to EC2
```

2022-10-03 19:48 UTC, Geph commented on setup_update.md
> +Follow the [update guide](./update.md) to see details on applying new changes to the API.
Done

2022-10-03 19:52 UTC, Geph commented
I think I got it all?

2022-10-05 02:07 UTC, jackah2 approved these changes

2022-10-05 02:07 UTC, merged